SHOW DATABASES ;
CREATE DATABASE IF NOT EXISTS R01_USERAUTH;
USE R01_USERAUTH;
CREATE TABLE IF NOT EXISTS ZCREDENTIAL (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
USERNAME VARCHAR(30) UNIQUE NOT NULL,
PASSWORD VARCHAR(30) NOT NULL
);
DESC ZCREDENTIAL;
INSERT INTO
ZCREDENTIAL
VALUES
(1, "ADMIN", "ADMIN"),
(2, "TestUser1", "1234567890-"),
(3, "TestUser2", "-0987654321"),
(NULL, "TEST", "TEST")
;
SELECT * FROM ZCREDENTIAL;